apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: valyria
spec:
  hosts:
  - ssh:
      address: 10.0.1.20
      user: ansible
      port: 22
      keyPath: /home/audun/.ssh/k0s.pem
    role: "controller+worker"
  - ssh:
      address: 10.0.1.21
      user: ansible
      port: 22
      keyPath: /home/audun/.ssh/k0s.pem
    role: worker
  - ssh:
      address: 10.0.1.22
      user: ansible
      port: 22
      keyPath: /home/audun/.ssh/k0s.pem
    role: worker
  - ssh:
      address: 10.0.1.23
      user: ansible
      port: 22
      keyPath: /home/audun/.ssh/k0s.pem
    role: worker
  k0s:
    version: 1.25.2+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
